using System.Text;
using SboxAssetLib.Core.Model;

namespace SboxAssetLib.Core.Import;

/// <summary>
/// Generates a Source 2 / s&amp;box <c>.vmat</c> material (using <c>shaders/complex.shader</c>)
/// from a set of PBR maps. Texture paths are addon-relative (e.g.
/// "materials/sboxassetlib/polyhaven/rock_01/rock_01_color.png").
///
/// Kept dependency-free and portable so the s&amp;box editor plugin can compile the same code.
///
/// Reference for the field/flag set: https://github.com/kaa992/batchVmatcreator
/// </summary>
public static class VmatWriter
{
    public static string Write(
        IReadOnlyDictionary<MapType, string> maps,
        NormalConvention normal = NormalConvention.OpenGl,
        ModelTextureScale? textureScale = null)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// THIS FILE IS AUTO-GENERATED BY sbox-asset-lib");
        sb.AppendLine();
        sb.AppendLine("Layer0");
        sb.AppendLine("{");
        sb.AppendLine("\tshader \"shaders/complex.shader\"");
        sb.AppendLine();

        var usesSpecular = maps.ContainsKey(MapType.Roughness)
            || maps.ContainsKey(MapType.Metalness)
            || maps.ContainsKey(MapType.Specular);

        var usesAlphaTest = maps.ContainsKey(MapType.Opacity);

        // ---- PBR feature toggles ----
        if (usesSpecular)
        {
            sb.AppendLine("\t//---- PBR ----");
            sb.AppendLine("\tF_SPECULAR 1");
            sb.AppendLine();
        }

        // ---- Alpha test ---- (cutout for foliage; render backfaces so thin geometry shows both sides.
        // F_ALPHA_TEST and F_TRANSLUCENT are mutually exclusive in complex.shader.)
        if (usesAlphaTest)
        {
            sb.AppendLine("\t//---- Alpha Test ----");
            sb.AppendLine("\tF_ALPHA_TEST 1");
            sb.AppendLine("\tF_RENDER_BACKFACES 1");
            sb.AppendLine();
        }

        // ---- Colour ----
        sb.AppendLine("\t//---- Color ----");
        sb.AppendLine("\tg_flModelTintAmount \"1.000\"");
        sb.AppendLine("\tg_vColorTint \"[1.000000 1.000000 1.000000 1.000000]\"");
        if (maps.TryGetValue(MapType.Albedo, out var color))
            sb.AppendLine($"\tTextureColor \"{color}\"");
        sb.AppendLine();

        // ---- Translucency / Alpha mask ---- (feeds the F_ALPHA_TEST cutout above)
        if (maps.TryGetValue(MapType.Opacity, out var opacity))
        {
            sb.AppendLine("\t//---- Translucency ----");
            sb.AppendLine("\tg_flAlphaTestReference \"0.500\"");
            sb.AppendLine("\tg_flAntiAliasedEdgeStrength \"1.000\"");
            sb.AppendLine($"\tTextureTranslucency \"{opacity}\"");
            sb.AppendLine();
        }

        // ---- Normal ---- (orientation is decided by which source was downloaded; see NormalConvention)
        if (maps.TryGetValue(MapType.Normal, out var nrm))
        {
            sb.AppendLine($"\t//---- Normal ({normal}) ----");
            sb.AppendLine($"\tTextureNormal \"{nrm}\"");
            sb.AppendLine();
        }

        // ---- Roughness ----
        if (maps.TryGetValue(MapType.Roughness, out var rough))
        {
            sb.AppendLine("\t//---- Roughness ----");
            sb.AppendLine($"\tTextureRoughness \"{rough}\"");
            sb.AppendLine();
        }

        // ---- Metalness ---- (the feature flag must be set or the texture is ignored)
        if (maps.TryGetValue(MapType.Metalness, out var metal))
        {
            sb.AppendLine("\t//---- Metalness ----");
            sb.AppendLine("\tF_METALNESS_TEXTURE 1");
            sb.AppendLine("\tg_flMetalness \"0.000\"");
            sb.AppendLine($"\tTextureMetalness \"{metal}\"");
            sb.AppendLine();
        }

        // ---- Ambient Occlusion ----
        if (maps.TryGetValue(MapType.AmbientOcclusion, out var ao))
        {
            sb.AppendLine("\t//---- Ambient Occlusion ----");
            sb.AppendLine("\tF_AMBIENT_OCCLUSION_TEXTURE 1");
            sb.AppendLine($"\tTextureAmbientOcclusion \"{ao}\"");
            sb.AppendLine();
        }

        // ---- Height / Parallax ---- (verify behaviour in-engine; left as a plain input for now)
        if (maps.TryGetValue(MapType.Height, out var height))
        {
            sb.AppendLine("\t//---- Height ----");
            sb.AppendLine($"\tTextureHeight \"{height}\"");
            sb.AppendLine();
        }

        // ---- Self Illum ----
        if (maps.TryGetValue(MapType.Emission, out var emission))
        {
            sb.AppendLine("\t//---- Self Illum ----");
            sb.AppendLine("\tF_SELF_ILLUM 1");
            sb.AppendLine($"\tTextureSelfIllumMask \"{emission}\"");
            sb.AppendLine();
        }

        if (textureScale is not null)
        {
            sb.AppendLine("\t//---- Texture Coordinates ----");
            sb.AppendLine($"\tg_vTexCoordScale \"[{Number(textureScale.U)} {Number(textureScale.V)}]\"");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string Number(double value) =>
        value.ToString("0.0###", System.Globalization.CultureInfo.InvariantCulture);
}
